import type { PortfolioProject } from "@/features/projects/types/project.types";

export const projects: PortfolioProject[] = [
  {
    id: 1,
    slug: "rehema-os",
    title: "REHEMA OS",
    category: "Intelligence artificielle",
    status: "En développement",
    summary: "Un assistant personnel pensé comme un ensemble de services capables d’analyser et d’orchestrer des commandes.",
    description: "REHEMA OS explore une architecture d’assistant personnel local-first. Le projet sépare l’orchestration, l’inférence, les outils et la persistance pour pouvoir faire évoluer chaque service sans reconstruire tout le système.",
    outcome: "Architecture distribuée : passerelle API, orchestration, IA locale, services Python, PostgreSQL et Docker.",
    tags: ["Ollama", "Python", "Docker", "Microservices"],
    featured: true,
  },
  {
    id: 2,
    slug: "codel-academy",
    title: "Codel Academy",
    category: "Éducation",
    status: "En développement",
    summary: "Une plateforme d’apprentissage structurée pour faire évoluer séparément le produit web, l’API et les outils partagés.",
    description: "Codel Academy est une base de plateforme EdTech conçue autour de parcours, de contenus et d’exercices progressifs. Son architecture monorepo rend explicites les frontières entre le frontend, l’API et les paquets communs.",
    outcome: "Monorepo Turborepo avec NestJS, Prisma, PostgreSQL et environnement conteneurisé.",
    tags: ["NestJS", "PostgreSQL", "Turborepo", "Prisma"],
    featured: true,
  },
  {
    id: 3,
    slug: "rm-study",
    title: "RM Study",
    category: "Éducation",
    status: "Prototype",
    summary: "Une expérience d’apprentissage numérique conçue pour progresser à son rythme avec des contenus contextualisés.",
    description: "RM Study rassemble cours, ressources et suivi de progression dans une expérience simple. Le prototype sert à tester une approche pédagogique accessible avant d’investir dans une plateforme plus large.",
    outcome: "Cours, ressources pédagogiques, tutorat et suivi de progression dans une interface accessible.",
    tags: ["EdTech", "Mobile", "UX"],
    image: "/images/rm-study.png",
    featured: true,
  },
  {
    id: 4,
    slug: "rehema-beats",
    title: "REHEMA Beats",
    category: "Produit numérique",
    status: "Concept",
    summary: "Un écosystème musical tourné vers les artistes, la publication de contenus et l’écoute en ligne.",
    description: "Une exploration produit autour de la diffusion musicale locale, de la gestion des artistes et de la publication de médias. La phase actuelle porte sur les contraintes de stockage et de diffusion.",
    outcome: "Gestion des artistes, médias, utilisateurs et diffusion avec une attention portée aux coûts d’hébergement.",
    tags: ["Kotlin", "Streaming", "Mobile"],
  },
  {
    id: 5,
    slug: "mathforge",
    title: "MathForge",
    category: "Éducation",
    status: "Prototype",
    summary: "Une application pour relier les mathématiques aux usages concrets de l’informatique et des réseaux.",
    description: "MathForge transforme des notions abstraites en petits parcours appliqués à l’algorithmique, aux données et aux réseaux. L’expérience mobile privilégie la progression courte et la pratique.",
    outcome: "Parcours progressifs, exercices interactifs et interface Android inspirée de Material Design 3.",
    tags: ["Android", "Kotlin", "EdTech"],
  },
  {
    id: 6,
    slug: "rehema-langue",
    title: "Rehema Langue",
    category: "Éducation",
    status: "Prototype",
    summary: "Une application Android d’apprentissage des langues organisée autour de leçons courtes et progressives.",
    description: "Le prototype teste une progression par micro-leçons, répétition et contexte. L’IA reste une piste d’évolution et non une promesse de la version actuelle.",
    outcome: "Architecture Kotlin et pistes de personnalisation future par intelligence artificielle.",
    tags: ["Android", "Kotlin", "IA"],
  },
  {
    id: 7,
    slug: "rechat",
    title: "ReChat",
    category: "Produit numérique",
    status: "Concept",
    summary: "Une application de messagerie avec comptes utilisateurs et conversations en temps réel.",
    description: "ReChat est une étude d’architecture portant sur l’identité, la synchronisation et la modération d’une messagerie moderne, avant toute implémentation à grande échelle.",
    outcome: "Étude d’une architecture d’authentification, de données temps réel et d’API évolutive.",
    tags: ["Mobile", "Backend", "Temps réel"],
  },
  {
    id: 8,
    slug: "nircia-shop",
    title: "Nircia Shop",
    category: "Commerce",
    status: "Concept",
    summary: "Une base de produit e-commerce couvrant catalogue, commandes et administration.",
    description: "Le projet formalise les principaux flux d’une boutique en ligne : découverte du catalogue, panier, commande et gestion opérationnelle.",
    outcome: "Modélisation des produits, catégories, utilisateurs, commandes et opérations du tableau de bord.",
    tags: ["Full-stack", "E-commerce", "Base de données"],
  },
  {
    id: 9,
    slug: "explore-kolwezi",
    title: "Explore Kolwezi",
    category: "Impact local",
    status: "Concept",
    summary: "Une vitrine numérique pour découvrir les lieux, les services, la culture et les initiatives de Kolwezi.",
    description: "Explore Kolwezi imagine un répertoire éditorial et cartographique construit avec les acteurs locaux, utile autant aux résidents qu’aux visiteurs.",
    outcome: "Un point d’entrée communautaire pour les habitants, les visiteurs et les entreprises locales.",
    tags: ["Web", "Tourisme", "Communauté"],
  },
  {
    id: 10,
    slug: "tests-recrutement",
    title: "Tests & recrutement",
    category: "Produit numérique",
    status: "Concept",
    summary: "Une plateforme SaaS pour administrer des évaluations de recrutement et restituer les résultats.",
    description: "Le concept couvre la création d’évaluations, l’accès sécurisé des candidats et une restitution claire pour les équipes de recrutement.",
    outcome: "Questionnaires, accès candidat, chronométrage, rapports et espace d’administration.",
    tags: ["SaaS", "B2B", "PDF"],
  },
  {
    id: 11,
    slug: "rehema-api",
    title: "Rehema API",
    category: "Infrastructure",
    status: "Concept",
    summary: "Une couche de services réutilisables destinée à réduire la duplication entre plusieurs produits.",
    description: "Rehema API organise des briques communes — identité, médias, notifications et observabilité — pour éviter de les réécrire dans chaque expérimentation.",
    outcome: "Passerelle API, modules partagés, documentation, journalisation et supervision.",
    tags: ["API", "Backend", "Infrastructure"],
  },
  {
    id: 12,
    slug: "rm-tech",
    title: "RM Tech",
    category: "Impact local",
    status: "Activité",
    summary: "Une micro-entreprise technologique cofondée pour accompagner les besoins numériques locaux.",
    description: "RM Tech relie apprentissage, accompagnement et réalisation de solutions numériques adaptées aux organisations locales.",
    outcome: "Développement web et mobile, conseil technique, formation et solutions sur mesure.",
    tags: ["Conseil", "Développement", "Formation"],
    image: "/images/rm_logo.png",
  },
  {
    id: 13,
    slug: "union-company-sarl",
    title: "Union Company SARL",
    category: "Commerce",
    status: "Activité",
    summary: "Une initiative commerciale et de services construite autour de besoins d’entreprises locales.",
    description: "Une activité de proximité qui associe commerce général, distribution et services destinés aux entreprises de Kolwezi.",
    outcome: "Commerce général, services B2B, distribution et accompagnement de proximité.",
    tags: ["B2B", "Services", "Commerce"],
    image: "/images/unoncompanysarl.jpg",
  },
  {
    id: 14,
    slug: "rehema-chain",
    title: "Rehema Chain",
    category: "Recherche",
    status: "Concept",
    summary: "Une exploration des architectures blockchain et des actifs numériques appliqués à un écosystème local.",
    description: "Une étude technique et économique destinée à comprendre les compromis d’un registre distribué, sans présentation trompeuse d’un produit déjà opérationnel.",
    outcome: "Étude de réseau, transactions, portefeuilles, nœuds et modèle économique — sans promesse de production.",
    tags: ["Blockchain", "Recherche", "Architecture"],
  },
];

export const projectCategories = ["Tous", ...new Set(projects.map((project) => project.category))];

export function getProjectBySlug(slug: string) {
  return projects.find((project) => project.slug === slug);
}
